# Generated by Django 3.0.3 on 2020-02-27 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_name', models.CharField(max_length=400, verbose_name='Наименование исследования')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, verbose_name='Описание исследования')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 related_name='researches', related_query_name='researches',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Создатель исследования')),
            ],
            options={
                'verbose_name_plural': 'Исследования',
                'unique_together': {('research_name', 'created_by'), ('research_name', 'created_at')},
            },
        ),
    ]
